In [1]:
import requests, sys, json
import itertools
import redis
import pandas as pd
from Bio.Blast import NCBIXML
from pprint import pprint
from Bio import SeqIO
from Bio.Blast import NCBIWWW

In [ ]:
###
### NOT PROJECT ###
###

The followiing fetches gene info using NCBI's API:

In [ ]:
# Using NCBI's API to look up a specific gene:
def fetch_endpoint(server, request, content_type):
    r = requests.get(server + request, headers = { "Content-Type" : content_type})
    if not r.ok:
        r.raise_for_status()
        sys.exit()
    if content_type == 'application/json':
        return r.json()
    else:
        return r.text

In [ ]:
server = "http://rest.ensembl.org/"
ext = "lookup/id/ENSG00000157764?"
con = "application/json"

In [ ]:
get_gene = fetch_endpoint(server, ext, con)

In [ ]:
pprint (get_gene)

In [ ]:
type(get_gene)

In [ ]:
#######
####### Start of Project 
#######

In [ ]:
# Starting Redis:

In [ ]:
# from the command line:

# connecting to the redis server:
# redis-server /etc/redis/6379.conf

# to connect to the command line interface:
# redis-cli

# check if the server is on:
# 127.0.0.1:6379> PING

# process id of Redis server:
# pgrep redis-server

# to clear out databases in Redis:
# 127.0.0.1:6379> FLUSHDB

# to quit Redis client:
# 127.0.0.1:6379> QUIT

# for more help:
# see https://realpython.com/python-redis/ for Redis -> Python guide

In [ ]:
# Using BBmap to reformat/resize fasta file (also from command line).
# for example:
# reformat.sh in=srr.fasta out=100k.fasta reads=100000

# Connecting to the Redis Client

In [2]:
#r = redis.Redis(db=5) to create database #5
r = redis.Redis(db = 5)

In [ ]:
# practice code
#r.mset({"Croatia": "Zagreb", "Bahamas": "Nassau"})

In [ ]:
#r.get("Bahamas")

In [ ]:
# working with Velotta lab sequence data:

In [ ]:
# parses fastq file and prints the ID, sequence, and length:
for seq_record in SeqIO.parse("100k.fastq", "fastq"):
    print(seq_record.id)
    print(repr(seq_record.seq))
    print(len(seq_record))
    print('')

The above implies a hierarchy in what the formats can store: FASTA ⊂ FASTQ ⊂ SAM.


In a typical high-throughput analysis workflow, you will encounter all three file types:


- FASTA to store the reference genome/transcriptome that the sequence fragments will be mapped to.
- FASTQ to store the sequence fragments before mapping.
- SAM/BAM to store the sequence fragments after mapping.

for future work, how to work with SAM files:
http://samtools.github.io/hts-specs/SAMv1.pdf

In [ ]:
# Reading in a fastq file using BioPython and saving it as a dictionary:
srr_dict = SeqIO.to_dict(SeqIO.parse("100k.fastq", "fastq"))

In [ ]:
list(srr_dict.keys())[2]

In [ ]:
# Shows all sequence IDs:
#list(srr_dict.keys())

In [ ]:
# printing a specific key's value:
srr_dict['SRR12726684.3']

In [ ]:
#df = pd.DataFrame(srr_dict)

In [ ]:
#df

In [ ]:
#df2 = pd.DataFrame.from_dict(srr_dict, orient='index')

In [ ]:
#df2

In [26]:
# reads-in fastq and assigns all parts of files to lists of related items:
ids = []
lengths = []
names = []
descr = []
dbx = []
la = []
seq = []
with open('10k.fastq') as fasta_file:  # Will close handle cleanly
    for seq_record in SeqIO.parse(fasta_file, 'fastq'):  # (generator)
        ids.append(seq_record.id)
        lengths.append(len(seq_record.seq))
        seq.append(str(seq_record.seq))
        names.append(seq_record.name)
        descr.append(seq_record.description)
        dbx.append(seq_record.dbxrefs)
        la.append(dict(seq_record.letter_annotations))

In [27]:
Qfasta = pd.DataFrame(dict(Name = names, LetterAnn = la)).set_index(['IDs'])

In [28]:
ID_only = Qfasta.Name.str.split('.').str[0]
run_only = Qfasta.Name.str.split('.').str[1]
let_ann = Qfasta.LetterAnn.values

In [29]:
df_total = pd.DataFrame({'ID_only': ID_only.values, 
                    'RunNumber':run_only.values, 
                    'Name': names, 
                    'Full_ID':run_only.index, 
                    'Description': descr, 
                    'Sequence': seq,  
                    'LetterAnn': let_ann, 
                    'length': lengths, 
                    'Dbxrefs': dbx})

In [30]:
# Convert columns to string using map(str) method
#df_total['Sequence'] = df_total["Sequence"].map(str)

In [31]:
#full database
df_total

,ID_only,RunNumber,Name,Full_ID,Description,Sequence,LetterAnn,length,Dbxrefs
0,SRR12726684,1,SRR12726684.1,SRR12726684.1,SRR12726684.1 1 length=101,NCCAGGGCCTCACCAGAGGTCCTGGGTTCATCAATAAATATAGTTA...,"{'phred_quality': [0, 27, 27, 33, 33, 37, 37, ...",101,[]
1,SRR12726684,2,SRR12726684.2,SRR12726684.2,SRR12726684.2 2 length=101,GGCAGGGGTCTAGAGGAGCCTGTTCTATAATCGATAAACCCCGTTA...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
2,SRR12726684,3,SRR12726684.3,SRR12726684.3,SRR12726684.3 3 length=101,CACAGGGGAAGATGGAGCATACCATAAAAGCTCCAAAGGACGGCAG...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
3,SRR12726684,4,SRR12726684.4,SRR12726684.4,SRR12726684.4 4 length=101,GGATGGGGAAGCCGGGCGGTGGTGGTGCACGCCTTTAATCCCAGCA...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
4,SRR12726684,5,SRR12726684.5,SRR12726684.5,SRR12726684.5 5 length=101,ATAAGGGGAACTAGAGAGATATCTCAGCAGTTAAATGCACATATTA...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
...,...,...,...,...,...,...,...,...,...
9995,SRR12726684,9996,SRR12726684.9996,SRR12726684.9996,SRR12726684.9996 9996 length=101,CTCAGGGCGGGAATATCTGCTTCAGTACAACGACCCCAAACGCACA...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
9996,SRR12726684,9997,SRR12726684.9997,SRR12726684.9997,SRR12726684.9997 9997 length=101,TCCAGGGGGCATCGAGGCGGACGATGACCGGCTCAACAAGGTCATC...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
9997,SRR12726684,9998,SRR12726684.9998,SRR12726684.9998,SRR12726684.9998 9998 length=101,CACGGGCGAAGAATTTGTTCACCTCCAAGCATTTCATGAAAAAGCT...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
9998,SRR12726684,9999,SRR12726684.9999,SRR12726684.9999,SRR12726684.9999 9999 length=101,TTCTGGGGAGATTTACAGGAATCACGTATTAATTTAAAAAAAAAAA...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]
9999,SRR12726684,10000,SRR12726684.10000,SRR12726684.10000,SRR12726684.10000 10000 length=101,CACTGGGGGAGGTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...,"{'phred_quality': [33, 33, 33, 33, 33, 37, 37,...",101,[]

In [12]:
#df_noseq = df_total[['ID_only', 'RunNumber','Name','Full_ID','Description']]
#df_noseq.head()

,ID_only,RunNumber,Name,Full_ID,Description
0,SRR12726684,1,SRR12726684.1,SRR12726684.1,SRR12726684.1 1 length=101
1,SRR12726684,2,SRR12726684.2,SRR12726684.2,SRR12726684.2 2 length=101
2,SRR12726684,3,SRR12726684.3,SRR12726684.3,SRR12726684.3 3 length=101
3,SRR12726684,4,SRR12726684.4,SRR12726684.4,SRR12726684.4 4 length=101
4,SRR12726684,5,SRR12726684.5,SRR12726684.5,SRR12726684.5 5 length=101

In [13]:
# for future sorting
#df1 = df.sort_values('score',ascending = False).groupby('pidx').head(2)

In [32]:
# Creating a smaller database for BLAST use
df_seq = df_total[['Full_ID', 'Sequence']]
df_seq_sm = df_seq.head()
df_seq_sm

         Full_ID                                           Sequence
0  SRR12726684.1  NCCAGGGCCTCACCAGAGGTCCTGGGTTCATCAATAAATATAGTTA...
1  SRR12726684.2  GGCAGGGGTCTAGAGGAGCCTGTTCTATAATCGATAAACCCCGTTA...
2  SRR12726684.3  CACAGGGGAAGATGGAGCATACCATAAAAGCTCCAAAGGACGGCAG...
3  SRR12726684.4  GGATGGGGAAGCCGGGCGGTGGTGGTGCACGCCTTTAATCCCAGCA...
4  SRR12726684.5  ATAAGGGGAACTAGAGAGATATCTCAGCAGTTAAATGCACATATTA...

Parse XML BLAST data into a Record.Blast object.

Parses XML output from BLAST (direct use discouraged). This (now) returns a list of Blast records. Historically it returned a single Blast record. You are expected to use this via the parse or read functions.

In [33]:
new_seq = df_seq_sm['Sequence'].iloc[0]
xd = str(new_seq)
xd

'NCCAGGGCCTCACCAGAGGTCCTGGGTTCATCAATAAATATAGTTACAGTCAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTAAATTGGGAGAAACACACT'

In [34]:
# Working BLAST
#seq = 'NCCAGGGCCTCACCAGAGGTCCTGGGTTCATCAATAAATA'
result_handle = NCBIWWW.qblast("blastn", "nt", xd)
blast_result = open("my_blast.xml", "w")
blast_result.write(result_handle.read())
blast_result.close()
result_handle.close()

In [35]:
E_VALUE_THRESH = 1e-05

In [36]:
# this works! (creates lists of possible matches)
alignx = []
hspx = []
for record in NCBIXML.parse(open("my_blast.xml")):
    if record.alignments : #skip queries with no matches
        #print("QUERY: %s" % record.query[:60])
        for align in record.alignments:
            for hsp in align.hsps:
                if hsp.expect < E_VALUE_THRESH:
                    #print("MATCH: %s " % align.title[:60])
                    #print(hsp.expect)
                    alignx.append(align.title)
                    hspx.append(hsp.expect)

In [37]:
alignx[0]

'gi|224922740|ref|NR_027324.1| Rattus norvegicus H19, imprinted maternally expressed transcript (non-protein coding) (H19), long non-coding RNA'

In [38]:
# gene ID
ID_alignx = alignx[0].split('|')[0] +  alignx[0].split('|')[1]
ID_alignx

'gi224922740'

In [39]:
# Turning xml parse into a data table:

#from https://programtalk.com/vs4/python/4932/phageParser/
def parse_blast(resultfile): #takes in the BLAST result, outputs list that can be made into csv
    result_handle = open(resultfile)
    blast_records = NCBIXML.parse(result_handle)
    csv_list = []
    
    header = [  'Query',
                'Name', 'Length', 'Score', 'Expect',
                'QueryStart', 'QueryEnd',
                'SubjectStart', 'SubjectEnd'
            ]
    
    csv_list.append(header)
    count = 0
    for blast_record in blast_records:
        '''help(blast_record.alignments[0].hsps[0])''' # these give help info for the parts 
        '''help(blast_record.alignments[0])        '''
        count +=1
        
        query = blast_record.query
        for alignment in blast_record.alignments:

            name = alignment.title
           # print('Alignment ID:',alignment.title)
            length = alignment.length
            #print('Alignment length:',alignment.length)
            hsp = alignment.hsps[0] # I don't know if we will ever have more than one, so might as well take the first one.
           # print('hsp score:',hsp.score)
            score = hsp.score
            expect = hsp.expect
            querystart = hsp.query_start
            queryend = hsp.query_end
            subjectstart = hsp.sbjct_start
            subjectend = hsp.sbjct_end
            row = [query,name,length,score,expect,querystart,queryend,subjectstart,subjectend]
            csv_list.append(row)
            print()
            
    result_handle.close()
    return csv_list

In [41]:
xmlparse = parse_blast('my_blast.xml')
xmlparse[2]

['No definition line',
 'gi|169642191|gb|BC160921.1| Rattus norvegicus cDNA clone IMAGE:7461928',
 2103,
 143.0,
 5.35266e-26,
 2,
 80,
 2009,
 2087]

In [42]:
df_xmlparse = pd.DataFrame(xmlparse)
df_xmlparse

,0,1,2,3,4,5,6,7,8
0,Query,Name,Length,Score,Expect,QueryStart,QueryEnd,SubjectStart,SubjectEnd
1,No definition line,gi|224922740|ref|NR_027324.1| Rattus norvegicu...,2369,143.0,0.0,2,80,2275,2353
2,No definition line,gi|169642191|gb|BC160921.1| Rattus norvegicus ...,2103,143.0,0.0,2,80,2009,2087
3,No definition line,gi|51131|emb|X58196.1| M.musculus H19 mRNA,1899,141.0,0.0,2,79,1796,1873
4,No definition line,gi|298889025|emb|FQ223810.1| Rattus norvegicus...,328,135.0,0.0,2,76,254,328
5,No definition line,gi|68534369|gb|BC099104.1| Rattus norvegicus c...,2270,135.0,0.0,2,76,2196,2270
6,No definition line,gi|298888893|emb|FQ223682.1| Rattus norvegicus...,432,131.0,0.0,2,74,360,432
7,No definition line,gi|19264032|gb|BC025150.1| Mus musculus H19 fe...,1171,122.0,0.0,2,67,1106,1171
8,No definition line,gi|1315515462|gb|KY242301.1| Capra hircus H19 ...,6948,102.0,0.0,2,78,6817,6894
9,No definition line,gi|1820964098|ref|XR_004386787.1| PREDICTED: R...,2334,92.0,0.0,2,52,2284,2334
10,No definition line,gi|1768013851|ref|XM_031388942.1| PREDICTED: M...,2306,92.0,0.0,2,52,2256,2306
11,No definition line,gi|1211370224|ref|XM_021633676.1| PREDICTED: M...,2314,92.0,0.0,2,52,2264,2314
12,No definition line,gi|1195731081|ref|XR_002378419.1| PREDICTED: M...,2288,92.0,0.0,2,52,2238,2288
13,No definition line,gi|1195493625|ref|XR_002380501.1| PREDICTED: M...,2297,92.0,0.0,2,52,2247,2297
14,No definition line,gi|762006043|ref|NR_130974.1| Mus musculus H19...,2284,92.0,0.0,2,52,2233,2283
15,No definition line,gi|761631400|ref|NR_130973.1| Mus musculus H19...,2288,92.0,0.0,2,52,2237,2287
16,No definition line,gi|2147782729|ref|XR_006639366.1| PREDICTED: J...,2322,92.0,0.0,2,52,2272,2322
17,No definition line,gi|2025693870|ref|XR_001197480.3| PREDICTED: M...,2322,92.0,0.0,2,52,2272,2322
18,No definition line,gi|1929223714|ref|XM_028870783.2| PREDICTED: P...,2338,92.0,0.0,2,52,2282,2332
19,No definition line,gi|1908018239|ref|XR_004945460.1| PREDICTED: O...,2316,92.0,0.0,2,52,2266,2316
20,No definition line,gi|2970434|gb|AF049091.1|AF049091 Mus musculus...,41680,92.0,0.0,2,52,8083,8133
21,No definition line,gi|42734138|gb|AC013548.13| Mus musculus chrom...,220084,92.0,0.0,2,52,139841,139891
22,No definition line,gi|15667636|dbj|AP003183.2| Mus musculus genom...,101491,92.0,0.0,2,52,8113,8163
23,No definition line,gi|408407860|gb|AF116709.2| Homo sapiens PRO26...,803,88.0,0.0,2,80,82,2
24,No definition line,"gi|33874111|gb|BC010185.2| Homo sapiens H19, i...",445,88.0,0.0,2,80,345,425
25,No definition line,"gi|33870950|gb|BC007513.2| Homo sapiens H19, i...",1652,88.0,0.0,2,80,1565,1645
26,No definition line,"gi|68533528|gb|BC098439.1| Homo sapiens H19, i...",1765,88.0,0.0,2,80,1655,1735
27,No definition line,gi|1842143699|ref|XM_034497012.1| PREDICTED: A...,1212,87.0,0.0,2,52,1162,1212
28,No definition line,gi|1621887049|ref|XM_028786979.1| PREDICTED: G...,2292,87.0,0.0,2,52,2242,2292
29,No definition line,gi|2063367169|emb|OU015757.1| Acomys percivali...,78221726,87.0,0.0,2,52,22274500,22274450
30,No definition line,gi|2063366644|emb|OU015389.1| Acomys dimidiatu...,77604179,87.0,0.0,2,52,22307233,22307183
31,No definition line,gi|2063337464|emb|OU015370.1| Acomys kempi gen...,78196808,87.0,0.0,2,52,22148645,22148595
32,No definition line,gi|2052686377|ref|XR_005287201.2| PREDICTED: A...,2317,87.0,0.0,2,52,2267,2317
33,No definition line,gi|2038233427|ref|XR_005975776.1| PREDICTED: M...,2315,87.0,0.0,2,52,2265,2315
34,No definition line,gi|1894914071|emb|LR877216.1| Acomys russatus ...,79927262,87.0,0.0,2,52,22863772,22863722
35,No definition line,gi|33354295|gb|AC098563.6| Rattus norvegicus 1...,250414,87.0,0.0,2,52,152656,152706
36,No definition line,gi|77993065|emb|CT027994.2| M.spretus DNA sequ...,169471,87.0,0.0,2,52,136771,136821
37,No definition line,gi|57515|emb|X59864.1| Rat ASM15 gene,3996,87.0,0.0,2,52,3257,3307
38,No definition line,gi|1811248737|dbj|AP022691.1| Epinephelus fusc...,42713404,86.0,0.0,53,95,6380622,6380664
39,No definition line,gi|74208427|dbj|AK145379.1| Mus musculus 5 day...,2257,86.0,0.0,2,49,2208,2255
40,No definition line,gi|76779863|gb|BC106079.1| Homo sapiens cDNA c...,377,85.0,0.0,2,80,286,368
41,No definition line,gi|1491094763|ref|XR_258366.2| PREDICTED: Micr...,2287,83.0,0.0,2,50,2239,2287
42,No definition line,"gi|33991084|gb|BC015952.2| Homo sapiens H19, i...",1860,83.0,0.0,2,80,1777,1857
43,No definition line,gi|51134|emb|X07201.1| Mouse H19 gene,3058,83.0,0.0,2,52,2904,2953
44,No definition line,gi|2206707811|ref|XM_047080167.1| PREDICTED: L...,10922,82.0,0.0,39,85,7984,7937
45,No definition line,gi|2206707809|ref|XM_047080166.1| PREDICTED: L...,11005,82.0,0.0,39,85,8067,8020
46,No definition line,gi|2206707807|ref|XM_047080165.1| PREDICTED: L...,10662,82.0,0.0,39,85,7724,7677
47,No definition line,gi|2206707805|ref|XM_047080164.1| PREDICTED: L...,10667,82.0,0.0,39,85,7729,7682
48,No definition line,"gi|346712725|dbj|AK382846.1| Bombyx mori mRNA,...",2400,81.0,0.0,33,80,2254,2301
49,No definition line,gi|1558335976|gb|CP027278.1| Lateolabrax macul...,22884195,80.0,0.0,52,96,3986799,3986843
50,No definition line,gi|2041343221|gb|CP068755.1| Danio rerio strai...,45833048,80.0,0.0,32,80,43601541,43601587

In [ ]:
# try to get this to work, is not currently working

In [ ]:
server = 'http://rest.ensembl.org/'
ext2 = 'lookup/id/1820964098?'
con = 'application/json'

In [ ]:
get_gene2 = fetch_endpoint(server, ext2, con)

In [ ]:
#hspx

In [ ]:
# This works! (shows alignments)
for record in NCBIXML.parse(open("my_blast.xml")):
    for align in record.alignments:
            for hsp in align.hsps:
                print(hsp)
                print()

In [ ]:
#def remove_punctuation(x):
#    try:
 #       x = x.str.replace('[^\w\s]','')
#    except:
#        pass
#    return x

In [ ]:
#df_seq.apply(remove_punctuation)

In [ ]:
# these are the various attributes of a SeqRecord file:
for seq_record in SeqIO.parse("10k.fastq", "fastq"):
    print(seq_record.id)
    print(seq_record.seq)
    print(seq_record.name)
    print(seq_record.description)
    print(seq_record.dbxrefs)
    print(seq_record.letter_annotations)
    print('')

# Parts of a FASTA file

https://biopython.org/docs/1.75/api/Bio.SeqRecord.html

id: Identifier such as a locus tag (string)

seq: The sequence itself (Seq object or similar)

Additional attributes:
name: Sequence name, e.g. gene name (string)

description: Additional text (string)

dbxrefs: List of database cross references (list of strings)

features: Any (sub)features defined (list of SeqFeature objects)

annotations: Further information about the whole sequence (dictionary). Most entries are strings, or lists of strings.

letter_annotations: Per letter/symbol annotation (restricted dictionary). This holds Python sequences (lists, strings or tuples) whose length matches that of the sequence. A typical use would be to hold a list of integers representing sequencing quality scores, or a string representing the secondary structure.

In [ ]:
######

In [ ]:
###### randomness

In [ ]:
first_rec = dict(itertools.islice(srr_dict.items(), 1))

In [ ]:
first_rec

In [ ]:
type(first_rec)

In [ ]:
######

In [ ]:
######

In [ ]:
#viewing the mini dataframe
df_seq_sm

In [ ]:
#Converting the mini dataframe to a dictionary
seq_dict = df_seq_sm.set_index('Full_ID').T.to_dict('list')
seq_dict

In [ ]:
# print all dictionary keys
seq_dict.keys()

In [ ]:
# print only the first dictionary key
list(seq_dict.keys())[0]

In [ ]:
#doesn't work so far
#with r.pipeline() as pipe:
#    for seq_id, seq in seq_dict.items():
#        print(seq_id)
#        print(seq)
        #pipe.hmset(seq_id, seq)
    #pipe.execute()

In [ ]:
# (hset) adds the first key/value pair to the Redis database (this code only adds the first record to the database)
# technically adds values to the Redis hash.
r.hset("Sequence", str(list(seq_dict.keys())[0]), str(list(seq_dict.values())[0]))

In [ ]:
# (hget) grabs sequence for the given key from Redis database
print(r.hget("Sequence", str(list(seq_dict.keys())[0])))

In [ ]:
# prints key value pairs in the seq_dict dictionary (the dictionary to be uploaded to Redis)
for i in seq_dict:
    print(i,'->',seq_dict[i])

In [ ]:
# adds key, values pairs to redis
for i in seq_dict:
    print(i,'->',seq_dict[i]) 
    r.hset("Sequence", str(i), str(seq_dict[i]))

In [ ]:
# grabs the sequence for given key
print(r.hget("Sequence", "SRR12726684.4"))

In [ ]:
# PySpark stuff:

In [ ]:
from pyspark.sql import Row
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

In [ ]:
df_spark = spark.createDataFrame(df_noseq)
df_spark.head(5)

In [ ]:
df_spark.show()
df_spark.printSchema()

In [ ]:
df_spark.show(1, vertical=True)

In [ ]:
df_spark.write.csv('foo.csv', header=True)
spark.read.csv('foo.csv', header=True).show()

In [ ]:
df_spark.createOrReplaceTempView("tableA")
spark.sql("SELECT count(*) from tableA").show()

In [ ]:
#probably don't need the following code:

In [ ]:
# do not use multiple times!!
blast_record = NCBIXML.read(result_handle)

In [ ]:
E_VALUE_THRESH = 0.04

In [ ]:
for alignment in blast_record.alignments:
    for hsp in alignment.hsps:
        if hsp.expect < E_VALUE_THRESH:
            print("****Alignment****")
            print("sequence:", alignment.title)
            print("length:", alignment.length)
            print("e value:", hsp.expect)
            print(hsp.query[0:75] + "...")
            print(hsp.match[0:75] + "...")
            print(hsp.sbjct[0:75] + "...")

In [ ]:
for alignment in blast_record.alignments:
    print(alignment)